### ISSUE TITLE
Error installing Education Domain

### ISSUE THREAD

**Issue by parthasai** [frappe/education#1]
### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.0.0-dev",
	"frappe": "14.0.0-dev"
}
```
### Route
```
Form/Domain Settings/Domain Settings
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 288, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1071, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 912, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1233, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 909, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/domain_settings/domain_settings.py", line 27, in on_update
    domain.setup_domain()
  File "apps/frappe/frappe/core/doctype/domain/domain.py", line 17, in setup_domain
    self.setup_data()
  File "apps/frappe/frappe/core/doctype/domain/domain.py", line 81, in setup_data
    self.data = frappe.get_domain_data(self.name)
  File "apps/frappe/frappe/__init__.py", line 821, in get_domain_data
    return _dict(get_attr(get_hooks("domains")[module][0] + ".data"))
  File "apps/frappe/frappe/__init__.py", line 1490, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1243, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'education.setup'

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 39, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 77, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1500, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 23, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 288, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 339, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1071, in run_post_save_methods
    self.run_method("on_update")
  File "apps/frappe/frappe/model/document.py", line 912, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1251, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1233, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 909, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/domain_settings/domain_settings.py", line 27, in on_update
    domain.setup_domain()
  File "apps/frappe/frappe/core/doctype/domain/domain.py", line 17, in setup_domain
    self.setup_data()
  File "apps/frappe/frappe/core/doctype/domain/domain.py", line 81, in setup_data
    self.data = frappe.get_domain_data(self.name)
  File "apps/frappe/frappe/__init__.py", line 821, in get_domain_data
    return _dict(get_attr(get_hooks("domains")[module][0] + ".data"))
  File "apps/frappe/frappe/__init__.py", line 1490, in get_attr
    return getattr(get_module(modulename), methodname)
  File "apps/frappe/frappe/__init__.py", line 1243, in get_module
    return importlib.import_module(modulename)
  File "/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'education.setup'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"Domain Settings\",\"owner\":\"Administrator\",\"modified\":\"2022-05-23 09:11:54.160612\",\"modified_by\":\"Administrator\",\"docstatus\":0,\"idx\":\"0\",\"doctype\":\"Domain Settings\",\"active_domains\":[{\"docstatus\":0,\"doctype\":\"Has Domain\",\"name\":\"new-has-domain-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"parent\":\"Domain Settings\",\"parentfield\":\"active_domains\",\"parenttype\":\"Domain Settings\",\"idx\":1,\"domain\":\"Education\"}],\"__last_sync_on\":\"2022-05-23T03:49:52.033Z\",\"__unsaved\":1}",
		"action": "Save"
	},
	"btn": {
		"jQuery3600104424923983997051": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 421,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "ModuleNotFoundError: No module named 'education.setup'"
}
```

**Comment by deepeshgarg007** [comment]
Fixed via https://github.com/frappe/education/pull/3
