### ISSUE TITLE
Issue in validate user .

### ISSUE THREAD

**Issue by muhammadmp** [frappe/education#116]
### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.17.4",
	"frappe": "14.26.2"
}
```
### Route
```
Form/Student/new-student-2
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1040, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 909, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 906, in fn
    return method_object(*args, **kwargs)
  File "apps/education/education/education/doctype/student/student.py", line 19, in validate
    self.validate_user()
  File "apps/education/education/education/doctype/student/student.py", line 68, in validate_user
    student_user.add_roles("Student")
  File "apps/frappe/frappe/core/doctype/user/user.py", line 498, in add_roles
    self.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 450, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 909, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1241, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 906, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 48, in autoname
    self.email = self.email.strip().lower()
AttributeError: 'NoneType' object has no attribute 'strip'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Student\",\"name\":\"new-student-1\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"Administrator\",\"enabled\":1,\"naming_series\":\"EDU-STU-.YYYY.-\",\"joining_date\":\"2023-03-30\",\"blood_group\":\"\",\"country\":\"India\",\"first_name\":\"muhammad\",\"last_name\":\"mp\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery360015275112652036051": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1181,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs"
}
```
### Response Data
```
{
	"exception": "AttributeError: 'NoneType' object has no attribute 'strip'"
}
```

**Comment by precihole** [comment]
Hello @pateljannat ,

In **Student** DocType User is automatically created on creation of student then there is an issue if we not enter any email id of student then it will throw an error as showing below,

![image](https://user-images.githubusercontent.com/111174201/230000535-5bbf44e8-b477-411e-ae31-4445dca09864.png)

Kindly Mandatory the email id field in Student DocType or add throw message for email id is mandatory for creation of user.

Because you allow the User creation by Default or we can skip it in Education settings

![image](https://user-images.githubusercontent.com/111174201/230001195-8eb1798e-c28d-42cd-b086-6d73d2e5f35d.png)


Regards,
Rehan Ansari
