### ISSUE TITLE
Student and Guardian Contact Details Report

### ISSUE THREAD

**Issue by msalim79** [frappe/education#149]
On running this report we get the following error -

ERPNext: v13.49.10 (version-13)

Frappe Framework: v13.52.0 (version-13)

![Student Guardian List Report Error](https://github.com/frappe/education/assets/30749464/33000da8-a8f5-4391-95a8-5f9666e50e8c)

"### App Versions
```
{
	"erpnext": "13.49.10",
	"frappe": "13.52.0"
}
```
### Route
```
query-report/Student and Guardian Contact Details
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 38, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 76, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1473, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 772, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 251, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
  File "apps/frappe/frappe/__init__.py", line 772, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 96, in generate_report_result
    result = normalize_result(result, columns)
  File "apps/frappe/frappe/desk/query_report.py", line 141, in normalize_result
    row_obj[column_name] = row[idx]
IndexError: list index out of range

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Student and Guardian Contact Details",
		"filters": "{\"academic_year\":\"2023\",\"program\":\"Grade 0\",\"student_batch_name\":\"Grade 0\"}"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run"
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range"
}
```

**Comment by Sudhegan** [comment]
same error for the following versions

### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "15.0.0",
	"frappe": "15.0.2",
	"hrms": "15.2.0",
	"india_compliance": "15.0.0-dev",
	"payments": "0.0.1",
	"print_designer": "1.0.0"
}
```
### Route
```
query-report/Student and Guardian Contact Details
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 847, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 221, in run
    result = generate_report_result(report, filters, user, custom_columns, is_tree, parent_field)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 847, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 88, in generate_report_result
    result = normalize_result(result, columns)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/query_report.py", line 133, in normalize_result
    row_obj[column_name] = row[idx]
                           ~~~^^^^^
IndexError: list index out of range

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"report_name": "Student and Guardian Contact Details",
		"filters": "{\"academic_year\":\"2023-2024\",\"program\":\"Tenth STD\",\"student_batch_name\":\"A\"}",
		"ignore_prepared_report": false,
		"are_default_filters": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.query_report.run",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "IndexError: list index out of range",
	"exc_type": "IndexError"
}
````

**Comment by RitvikSardana** [comment]
Fixed it https://github.com/frappe/education/pull/154
