### ISSUE TITLE
Issue on Data Import: Student details csv importing fails with AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by shakkeert** [frappe/education#177]
Student Import with Data Import option is not working, even tested with mandatory fields of records.
Import error log shows following traceback for each row.

```
Traceback (most recent call last):
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 148, in import_data
    doc = self.process_doc(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 242, in process_doc
    return self.insert_record(doc)
  File "apps/frappe/frappe/core/doctype/data_import/importer.py", line 261, in insert_record
    new_doc.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1271, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1253, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/education/education/education/doctype/student/student.py", line 19, in validate
    self.validate_user()
  File "apps/education/education/education/doctype/student/student.py", line 68, in validate_user
    student_user.add_roles("Student")
  File "apps/frappe/frappe/core/doctype/user/user.py", line 508, in add_roles
    self.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 254, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 450, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 167, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1271, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1253, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 911, in fn
    return method_object(*args, **kwargs)
  File "apps/frappe/frappe/core/doctype/user/user.py", line 49, in autoname
    self.email = self.email.strip().lower()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by RitvikSardana** [comment]
Which version are you using ?
@shakkeert

**Comment by shakkeert** [comment]
Following are the versions i currently using..
OS: Ubuntu 22.04 x64
frappe: 14.43.1
Erpnext: 14.33.2
Education: 15.0.0

**Comment by RitvikSardana** [comment]
It is working perfectly fine with version 15 of frappe and erpnext
