### ISSUE TITLE
Fees Failed to be Created.

### ISSUE THREAD

**Issue by Kubelaikhan** [frappe/education#186]
What's happen? I already assigned the AR for my School, but it cannot be done.

request.js:268 
        
        
       POST http://127.0.0.1:8000/api/method/frappe.desk.form.save.savedocs 417 (EXPECTATION FAILED)
send @ jquery.js:10109
ajax @ jquery.js:9690
frappe.request.call @ request.js:268
frappe.call @ request.js:105
_call @ save.js:245
save @ save.js:23
frappe.ui.form.save @ save.js:272
(anonymous) @ form.js:808
Promise.then (async)
(anonymous) @ dom.js:262
frappe.run_serially @ dom.js:260
validate_and_save @ form.js:799
(anonymous) @ form.js:738
save @ form.js:735
(anonymous) @ form.js:830
Promise.then (async)
(anonymous) @ form.js:825
primary_action @ messages.js:34
(anonymous) @ dialog.js:163
dispatch @ jquery.js:5430
elemData.handle @ jquery.js:5234
Show 4 more frames
Show less
request.js:457

 Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 95, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 47, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1620, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 31, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 361, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/education/education/education/doctype/fees/fees.py", line 92, in on_submit
    self.make_gl_entries()
  File "apps/education/education/education/doctype/fees/fees.py", line 143, in make_gl_entries
    make_gl_entries(
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 43, in make_gl_entries
    save_entries(gl_map, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 364, in save_entries
    make_entry(entry, adv_adj, update_outstanding, from_repost)
  File "apps/erpnext/erpnext/accounts/general_ledger.py", line 375, in make_entry
    gle.submit()
  File "apps/frappe/frappe/model/document.py", line 1006, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 985, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 309, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 331, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 262, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1054, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 915, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1277, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1259, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 912, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 46, in validate
    self.check_mandatory()
  File "apps/erpnext/erpnext/accounts/doctype/gl_entry/gl_entry.py", line 87, in check_mandatory
    frappe.throw(_("{0} is required").format(_(self.meta.get_label(k))))
  File "apps/frappe/frappe/__init__.py", line 540, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 508, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 454, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Account is required

**Comment by RitvikSardana** [comment]
which version of ERPNext and Education?
@Kubelaikhan

**Comment by Kubelaikhan** [comment]
@RitvikSardana it's 14

**Comment by RitvikSardana** [comment]
both are on version 14? @Kubelaikhan

**Comment by Kubelaikhan** [comment]
I don't think there is another version of education module? But I already solved this, thank you! @RitvikSardana

**Comment by RitvikSardana** [comment]
There are actually 2 versions
1.  Version 15
2. Develop


New features will be coming directly on the Develop Branch.

You can try all the latest features on the develop branch
