### ISSUE TITLE
Error On Student Master - Connections FastTab

### ISSUE THREAD

**Issue by msalim79** [frappe/education#216]
![image](https://github.com/frappe/education/assets/30749464/7164bfa9-fb3d-4d7e-881b-1426f166a620)

### App Versions
```
{
	"builder": "1.4.0",
	"education": "15.2.1",
	"erpnext": "15.16.2",
	"frappe": "15.17.1"
}
```
### Route
```
Form/Student/EDU-STU-2024-00001
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1716, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 876, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/notifications.py", line 289, in get_open_count
    external_links_data_for_d = get_external_links(d, name, links)
  File "apps/frappe/frappe/desk/notifications.py", line 338, in get_external_links
    frappe.get_all(
  File "apps/frappe/frappe/__init__.py", line 2005, in get_all
    return get_list(doctype, *args, **kwargs)
  File "apps/frappe/frappe/__init__.py", line 1980, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "apps/frappe/frappe/model/db_query.py", line 192, in execute
    result = self.build_and_run()
  File "apps/frappe/frappe/model/db_query.py", line 233, in build_and_run
    return frappe.db.sql(
  File "apps/frappe/frappe/database/database.py", line 234, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
  File "env/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.10/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabSales Invoice.student' in 'where clause'")

```
### Request Data
```
{
	"type": "GET",
	"args": {
		"doctype": "Student",
		"name": "EDU-STU-2024-00001",
		"items": "[\"Sales Invoice\",\"Bank Account\",\"Program Enrollment\",\"Course Enrollment\",\"Student Log\",\"Student Group\",\"Assessment Result\",\"Student Attendance\",\"Student Leave Application\"]"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.notifications.get_open_count",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabSales Invoice.student' in 'where clause'\")",
	"exc_type": "OperationalError"
}
```

**Comment by RitvikSardana** [comment]
Not Replicable.

Can you share the SS of how your Sales Invoice DocType looks like.

Does it have student field?
@msalim79

**Comment by msalim79** [comment]
Negative does not have "student field"

![image](https://github.com/frappe/education/assets/30749464/cc323f28-b868-4e31-b200-6b59fbd5c5d1)

**Comment by RitvikSardana** [comment]
Hence the reason, I think it needs a migrate script to add all these columns in the Sales Invoice.

**Comment by RitvikSardana** [comment]
fixed via: @madar2020
