### ISSUE TITLE
Error in enrolling student applicants

### ISSUE THREAD

**Issue by Tomkar9** [frappe/education#236]
![Screenshot (15)](https://github.com/frappe/education/assets/91272550/3ec79843-b95a-40f2-80c8-f44210407b49)

this is the error i get when i try to enroll a student applicant after the person has fill the admission and has been approved

**Comment by RitvikSardana** [comment]
@Tomkar9 put steps to reproduce the same error, put some screenshots and some description about the error.

**Comment by Tomkar9** [comment]
Done

**Comment by RitvikSardana** [comment]
@Tomkar9, open your console by 
double clicking the mouse > Inspect > Console.

copy the traceback and send.

**Comment by Tomkar9** [comment]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1718, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/mapper.py", line 36, in make_mapped_doc
    return method(source_name)
           ^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/education/education/education/api.py", line 48, in enroll_student
    student.save()
  File "apps/frappe/frappe/model/document.py", line 335, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 357, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 284, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 494, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 164, in set_new_name
    set_name_from_naming_options(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
    _prompt_autoname(autoname, doc)
  File "apps/frappe/frappe/model/naming.py", line 523, in _prompt_autoname
    frappe.throw(_("Please set the document name"))
  File "apps/frappe/frappe/__init__.py", line 602, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 567, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 518, in _raise_exception
    raise exc
frappe.exceptions.ValidationError: Please set the document name
[request.js:473:14](http://10.10.60.18/apps/frappe/frappe/public/js/frappe/request.js)

​

**Comment by RitvikSardana** [comment]
@Tomkar9 
This is not replicable, can you share some other information, like Version of 

Education
ERPNext
Frappe

**Comment by Tomkar9** [comment]
Education. Version 15
ERPNext. Version 15
Frappe. Version 15

**Comment by Tomkar9** [comment]
Education: v15.0.0 (version-15)

ERPNext: v15.18.2 (version-15)

Frappe Framework: v15.19.0 (version-15)

**Comment by Tomkar9** [comment]
> @Tomkar9 This is not replicable, can you share some other information, like Version of
> 
> Education ERPNext Frappe



> @Tomkar9 This is not replicable, can you share some other information, like Version of
> 
> Education ERPNext Frappe
