### ISSUE TITLE
can't create assessment group

### ISSUE THREAD

**Issue by AliShaatani** [frappe/education#25]
Version Details

Education: v0.0.1 (develop)
ERPNext: v14.2.0 (HEAD)
Frappe Framework: v14.8.0 (HEAD)

I'm using V14, which the education domain, has to be installed manually
After the installation, when going to assessment group tree, i found that the parent group is "undefined"
![alt text](http://energypaths.ly/images/1.PNG "Preview the issue")

and as you know i need parent group to create child group, so when i call the parent name "undefined" in parent text box, it can't be called, or not exist 
![alt text](http://energypaths.ly/images/2.PNG "Preview the issue")

So, i can't create any group without callable parent, in my case there in non !!

in the ideal set up, you found All assessment group as the default parent
but, in my mine is "undefined"

**Comment by AliShaatani** [comment]
when i try to build the the tree this error shows up 
`### App Versions
```
{
	"education": "0.0.1",
	"erpnext": "14.2.3",
	"frappe": "14.10.0",
	"payments": "0.0.1"
}
```
### Route
```
Tree/Assessment Group
```
### Trackeback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 69, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1585, in call
    return fn(*args, **newargs)
TypeError: get_all_nodes() missing 2 required positional arguments: 'label' and 'parent'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doctype": "Assessment Group",
		"is_root": true,
		"tree_method": "frappe.desk.treeview.get_children"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.treeview.get_all_nodes"
}
```
### Response Data
```
{
	"exception": "TypeError: get_all_nodes() missing 2 required positional arguments: 'label' and 'parent'"
}
````
