### ISSUE TITLE
blank student portal even after not selecting skip create user for new student

### ISSUE THREAD

**Issue by Sudhegan** [frappe/education#252]
the student portal is blank 

the skip user creation for new student is not enable in education setting ever,

and it would be better if students are allowed only to the portal and not to the desk

error trackback from browser console:

> Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1761, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/education/education/education/api.py", line 521, in get_student_info
    student_info = frappe.db.get_list(
                   ^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

![image](https://github.com/frappe/education/assets/65366543/0c2c35aa-31a2-4d1a-a50f-629be566a8ea)

**Comment by RitvikSardana** [comment]
Irrelevant issue
