### ISSUE TITLE
AttributeError: 'EducationSettings' object has no attribute 'user_creation_skip'

### ISSUE THREAD

**Issue by zefanja** [frappe/education#31]
# Description of the issue
I have a student applicant. After Approving I want to enroll him/her in the program, but I get this error:
`AttributeError: 'EducationSettings' object has no attribute 'user_creation_skip'`

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.2.2
frappe 12.0.20

```

## Steps to reproduce the issue

1. Create a new student applicant
2. Approve him/her
3. Try to enroll him / her

### Observed result
`AttributeError: 'EducationSettings' object has no attribute 'user_creation_skip'`

### Expected result
Student should be enrolled and a new student should be created.

### Stacktrace
```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1042, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/mapper.py", line 30, in make_mapped_doc
    return method(source_name)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/education/api.py", line 36, in enroll_student
    student.save()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 272, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 295, in _save
    self.insert()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 253, in insert
    self.run_method("after_insert")
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 787, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1058, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 1041, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 781, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/education/doctype/student/student.py", line 43, in after_insert
    if not frappe.get_single('Education Settings').user_creation_skip:
AttributeError: 'EducationSettings' object has no attribute 'user_creation_skip'
```

**Comment by zefanja** [comment]
Seems to be related to frappe/erpnext#19122. The Field `user_creation_skip` does not show up in the education settings.

![grafik](https://user-images.githubusercontent.com/708888/70390729-2d446280-1a00-11ea-8d50-1fafd9c69429.png)

@theopen-institute @nabinhait @scmmishra

**Comment by fderyckel** [comment]
This has been addressed and can now be closed.

**Comment by pateljannat** [comment]
@zefanja  Unable to replicate this. Please make sure that all your apps are on the latest version.
