### ISSUE TITLE
Student Report Generation Tool Empty Display

### ISSUE THREAD

**Issue by BernMaina** [frappe/education#42]
## Description of the issue
After students marks are entered in the system, it expected that the report for the individual student can be produced. Using the Student Report Generation tool, reports are unable to be produced.

## Context information (for bug reports)

**Output of `bench version`**
```
ERPNEXT version 12
```

## Steps to reproduce the issue

Check the link below for further information and how to reproduce this issue.

https://discuss.erpnext.com/t/student-report-generation-tool-doesnt-display-student-results-on-report-printing/57999
### Observed result
Student report Generated is blank
### Expected result
Population of student report with the marks clearly visible for all courses.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1042, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 515, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 183, in run
    result = generate_report_result(report, filters, user)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/query_report.py", line 68, in generate_report_result
    res = report.execute_script_report(filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 104, in execute_script_report
    res = self.execute_module(filters)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/core/doctype/report/report.py", line 121, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/education/report/course_wise_assessment_report/course_wise_assessment_report.py", line 25, in execute
    frappe.throw(_("Please select the assessment group other than 'All Assessment Groups'"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 364, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 350, in msgprint
    _raise_exception()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 316, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Please select the assessment group other than 'All Assessment Groups'
```

**Comment by blessonfire** [comment]
I confirm this issue. For me, it just outputs a PDF file with "Student Attendance" and "Parent Teacher Meeting Attendance" headings. Rest everything is blank.

**Comment by imBentj** [comment]
Even I'm facing a similar issue, the pdf file just contains the entire "Student Academic details", "Student Attendance" & "Parents Teachers Meeting Attendance". Even after selecting the "Show Marks" checkbox, the result isn't being displayed.

Below I'm attaching a report card that I had generated.

[Report_Card_EDU-STU-2021-00003.pdf](https://github.com/frappe/erpnext/files/6282979/Report_Card_EDU-STU-2021-00003.pdf)

**Comment by rexson12** [comment]
I'm having ths same issues . I get output has pdf, the pdf contains only 'Students Attendance' and 'parents teachers meeting' heading else there is nothing present in the output.Everything is blank except for that Headings. I'm not getting the desired results which I aimed for.

**Comment by johnlongland** [comment]
I am running on V12.28 and it does give me results ? Perhaps if you update ? One thing I do not see , are totals. It gives the score for individual assessment criteria but not the total fro a course.

**Comment by MIrani0822** [comment]
Same issue with the report card. But there are no marks...
[Report_Card_EDU-STU-2022-00002.pdf](https://github.com/frappe/erpnext/files/9307022/Report_Card_EDU-STU-2022-00002.pdf)
@ankush, will it take long to validate this issue?

And once validated, how long do you think it might take to troubleshoot and resolve it?

**Comment by MIrani0822** [comment]
The issue is also being discussed on: [https://discuss.erpnext.com/t/student-report-generation-tool-doesnt-display-student-results-on-report-printing/57999]

**Comment by AliShaatani** [comment]
this issue still exist in V13, please move this issue to Education branch
